const CHANGE_MODAL_SLIDE = 'CHANGE_MODAL_SLIDE'
const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
const ADD_COMMENT = 'ADD_COMMENT'
const SET_ALERT = 'SET_ALERT'

export {
  CHANGE_MODAL_SLIDE,
  CHANGE_CURRENT_PAGE,
  ADD_COMMENT,
  SET_ALERT
}
