const CHANGE_MODAL_SLIDE = 'CHANGE_MODAL_SLIDE'
const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE'
const ADD_BLOG_COMMENT = 'ADD_BLOG_COMMENT'
const ADD_MATCH_COMMENT = 'ADD_MATCH_COMMENT'
const SET_ALERT = 'SET_ALERT'

export {
  CHANGE_MODAL_SLIDE,
  CHANGE_CURRENT_PAGE,
  ADD_BLOG_COMMENT,
  ADD_MATCH_COMMENT,
  SET_ALERT
}
